<h1>Exploring the datasets</h1>

Author of this notebook: Resia S. Kilic

In [128]:
# Importing pandas to use its functions
import pandas as pd

In [129]:
# Assigning the dataset local path to a variable
# Reading the excel file with pandas
sales_dt = pd.read_excel(r"C:\Users\Gebruiker\Downloads\Data Files\sales.xlsx")
metaclean_dt = pd.read_excel(r"C:\Users\Gebruiker\Downloads\Data Files\metaClean43Brightspace.xlsx")

# Viewining the column names and their data type
sales_dt.info()

# Viewing the first five rows of each dataset
sales_dt.head()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   opening_weekend           10929 non-null  float64
 9   theatre_count             10963 non-null  float64
 10  avg run per theatre       10952 non-null  float64
 11  runtime                   24559 non-null  float64
 12  keywords                  12517 non-null  object
 13  creative_type             26667 non-null  str
 14  url                       30612 non-null  str
dtypes: float64(8), int64(1), object(2), str(4)
memory usage: 3.5+ MB

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...

In [130]:
# Viewining the column names and their data type
metaclean_dt.info()

# Viewing the first five rows of each dataset
metaclean_dt.head()

<class 'pandas.DataFrame'>
RangeIndex: 11364 entries, 0 to 11363
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        11364 non-null  str
 1   title      11364 non-null  str
 2   studio     11014 non-null  str
 3   rating     10297 non-null  str
 4   runtime    11109 non-null  float64
 5   cast       7662 non-null   str
 6   director   11350 non-null  str
 7   genre      11344 non-null  str
 8   summary    5467 non-null   str
 9   awards     4387 non-null   str
 10  metascore  11364 non-null  int64
 11  userscore  9259 non-null   float64
 12  RelDate    11364 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(9)
memory usage: 1.1 MB

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

<h3>Profile MetaClean and Sales dataset</h3>

In [131]:
# Checking row and column counts of Sales and Metaclean
print("MetaClean rows and columns:", metaclean_dt.shape)
print("Sales rows and columns:", sales_dt.shape)

MetaClean rows and columns: (11364, 13)
Sales rows and columns: (30612, 15)

In [132]:
# Checking missing values
print("MetaClean missing values:\n" , metaclean_dt.isnull().sum())
print("MetaClean total missing values:\n" , sum(metaclean_dt.isnull().sum()))

MetaClean missing values:
 url             0
title           0
studio        350
rating       1067
runtime       255
cast         3702
director       14
genre          20
summary      5897
awards       6977
metascore       0
userscore    2105
RelDate         0
dtype: int64
MetaClean total missing values:
 20387

In [133]:
# Checking missing values
print("Sales missing values:\n" , sales_dt.isnull().sum())
print("Sales total missing values:\n" , sum(sales_dt.isnull().sum()))

Sales missing values:
 year                            0
release_date                    0
title                           8
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
opening_weekend             19683
theatre_count               19649
avg run per theatre         19660
runtime                      6053
keywords                    18095
creative_type                3945
url                             0
dtype: int64
Sales total missing values:
 151731