In [7]:
import pandas as pd
user_reviews = pd.read_excel(r'/Users/yg/Documents/Database management/Data Files - database/UserReviewsClean43LIWC.xlsx')

for column in user_reviews.columns:
    if user_reviews[column].nunique() == len(user_reviews): 
        print(column)

KeyboardInterrupt:

Finding out whether this column will be the primary key - no single column has completely unique, non-missing values.

In [ ]:
summary = pd.DataFrame({
        'Total Reviews': [len(user_reviews)],
        'Unique Users': [user_reviews.nunique()],
        'Missing Values': [user_reviews.isnull().sum().sum()],
        'Duplicate Values': [user_reviews.duplicated().sum()],
})

print(summary)

   Total Reviews                                       Unique Users  \
0         319662  url          11364
idvscore        16
reviewer...

   Missing Values  Duplicate Values
0           20793               922

erd = identification of how our tables are look 

we need to find: columns in the datasets, find the important columns that will be needed in those respective data sets. e.g. table from which director got the most sales - what do we need? Director? Sales? Sum of sales to each director -> How many sales has he/she done in total? (example)

In [ ]:
import pandas as pd
user_reviews = pd.read_excel(r'/Users/yg/Documents/Database management/Data Files - database/UserReviewsClean43LIWC.xlsx')

column_names = user_reviews.columns.tolist()

In [ ]:
import pandas as pd
user_reviews = pd.read_excel(r'/Users/yg/Documents/Database management/Data Files - database/UserReviewsClean43LIWC.xlsx')

#printing the top 10 rows of the dataframe
display(user_reviews.head(10))

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2,113,94.05,32.91,...,4.42,0.0,0.00,0.00,0.00,0.88,0,1.77,0.00,0.00
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1,103,57.11,38.53,...,0.97,0.0,0.00,0.00,0.00,0.00,0,1.94,5.83,0.00
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1,143,75.73,66.27,...,0.70,0.0,0.00,0.00,0.00,0.00,0,1.40,0.00,1.40
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1,14,83.81,23.75,...,0.00,0.0,0.00,0.00,0.00,0.00,0,14.29,0.00,0.00
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0,20,93.26,69.14,...,0.00,0.0,0.00,0.00,0.00,0.00,0,10.00,0.00,0.00
5,https://www.metacritic.com/movie/bronson,8,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",0,0,516,97.02,57.68,...,6.98,0.0,0.97,0.78,0.39,0.39,0,0.39,0.00,0.78
6,https://www.metacritic.com/movie/bronson,8,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",0,0,94,95.03,70.27,...,6.38,0.0,0.00,0.00,1.06,0.00,0,2.13,0.00,0.00
7,https://www.metacritic.com/movie/bronson,7,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,0,0,89,98.31,63.20,...,8.99,0.0,0.00,0.00,0.00,0.00,0,2.25,0.00,0.00
8,https://www.metacritic.com/movie/bronson,4,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,0,0,115,89.38,21.69,...,0.00,0.0,0.00,0.00,0.00,0.00,0,1.74,0.00,0.00
9,https://www.metacritic.com/movie/bronson,10,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,0,0,15,97.53,50.00,...,6.67,0.0,0.00,0.00,0.00,6.67,0,13.33,0.00,40.00

In [ ]:
import pandas as pd
user_reviews = pd.read_excel(r'/Users/yg/Documents/Database management/Data Files - database/UserReviewsClean43LIWC.xlsx')

#clean the data by removing any rows with missing values
clean_reviews = user_reviews.copy()
clean_reviews.columns = clean_reviews.columns.str.strip().str.lower().str.replace(" ", "_")

clean_reviews["idvscore"] = pd.to_numeric(clean_reviews["idvscore"], errors='coerce')

clean_reviews["reviewer"] = clean_reviews["reviewer"].astype("string").str.strip()
clean_reviews["url"] = clean_reviews["url"].astype("string").str.strip()

display(clean_reviews.isna().sum().sort_values(ascending=False))

thumbsup     3580
thumbstot    3576
datep        3413
rev          3413
idvscore     3409
             ...
number          0
interrog        0
compare         0
adj             0
otherp          0
Length: 100, dtype: int64

I learned how to clean the data. 
1. Standardize column names and data types.
2. Convert idvscore to numeric values.
3. Inspect missing values by column.
4. Investigate duplicate rows before deleting them.
5. Normalize reviewer and URL values.
6. Add a review_id primary key after deciding how duplicates should be handled.
7. Build the ERD from the cleaned columns.

importance of a surrogate key: to uniquely identify each row. 

giving every review a guranteed unique identifier. and provide a stable primary key even when columns such as 'reviewer', 'url', or review text repeeat.

In [8]:
clean_reviews.insert(0, "reviewer_id", range(1, len(clean_reviews) + 1))

In [11]:
user_reviews["idvscore_numeric"] = pd.to_numeric(
    user_reviews["idvscore"],
    errors="coerce"
)

top_reviews = (
    user_reviews
    .dropna(subset=["idvscore_numeric"])
    .sort_values("idvscore_numeric", ascending=False)
    [["url", "reviewer", "idvscore_numeric"]]
    .head(10)
)

display(top_reviews)

,url,reviewer,idvscore_numeric
159532,https://www.metacritic.com/movie/your-name,'GuetguetLeBG',10.0
153164,https://www.metacritic.com/movie/gaga-five-foo...,'caiopsico',10.0
153162,https://www.metacritic.com/movie/gaga-five-foo...,'VLee',10.0
153161,https://www.metacritic.com/movie/gaga-five-foo...,'Mrjon',10.0
153160,https://www.metacritic.com/movie/gaga-five-foo...,'Francisco25luis',10.0
153159,https://www.metacritic.com/movie/gaga-five-foo...,'CesarMenezes',10.0
153158,https://www.metacritic.com/movie/gaga-five-foo...,'guizuntini',10.0
153157,https://www.metacritic.com/movie/gaga-five-foo...,'ROMERITO',10.0
153156,https://www.metacritic.com/movie/gaga-five-foo...,'yedu16',10.0
153155,https://www.metacritic.com/movie/gaga-five-foo...,'Itswellison',10.0

In [19]:
df = pd.DataFrame(user_reviews)
df
num_of_rows = len(df)

In [20]:
print(user_reviews.shape)

(319662, 101)

In [21]:
summary = pd.DataFrame({
        'Total Reviews': [len(user_reviews)],
        'Unique Users': [user_reviews.nunique()],
        'Unique URLs':[user_reviews['url'].nunique()],
        'Unique Reviewers':[user_reviews['reviewer'].nunique()],
        'Missing Values': [user_reviews.isnull().sum().sum()],
        'Duplicate Values': [user_reviews.duplicated().sum()],
        "Duplicate Rows": [user_reviews.duplicated().sum()]
})

display(summary)

,Total Reviews,Unique Users,Unique URLs,Unique Reviewers,Missing Values,Duplicate Values,Duplicate Rows
0,319662,url 11364 idvscore ...,11364,106795,24202,922,922

In [22]:
print(user_reviews["idvscore_numeric"].describe())

count    316253.000000
mean          6.608184
std           3.185721
min           0.000000
25%           5.000000
50%           7.000000
75%           9.000000
max          10.000000
Name: idvscore_numeric, dtype: float64

In [27]:
scores = pd.to_numeric(
    user_reviews["idvscore"],
    errors="coerce"
)

invalid_scores = user_reviews.loc[
    scores.isna(),
    "idvscore"
]

print(invalid_scores.value_counts(dropna=False).head(1))

idvscore
NaN    3404
Name: count, dtype: int64

In [30]:
df = pd.read_excel(r'/Users/yg/Documents/Database management/Data Files - database/UserReviewsClean43LIWC.xlsx')

df_raw = df.copy()

df = df.dropna(subset=['reviewer'])
df = df.drop_duplicates()

print("---Cleaned Data Structure ---")
print(df.info())

print("\---Remaining Missing Values---")
print(df.isna().sum())

---Cleaned Data Structure ---
<class 'pandas.DataFrame'>
Index: 316131 entries, 0 to 319661
Data columns (total 100 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           316131 non-null  str
 1   idvscore      316130 non-null  object
 2   reviewer      316131 non-null  str
 3   dateP         316125 non-null  str
 4   Rev           316125 non-null  str
 5   thumbsUp      315957 non-null  object
 6   thumbsTot     315958 non-null  object
 7   WC            316131 non-null  int64
 8   Analytic      316131 non-null  float64
 9   Clout         316131 non-null  float64
 10  Authentic     316131 non-null  float64
 11  Tone          316131 non-null  float64
 12  WPS           316131 non-null  float64
 13  Sixltr        316131 non-null  float64
 14  Dic           316131 non-null  float64
 15  function      316131 non-null  float64
 16  pronoun       316131 non-null  float64
 17  ppron         316131 non-null  float64
 18  i             316131 non-null  float64
 19  we            316131 non-null  float64
 20  you           316131 non-null  float64
 21  shehe         316131 non-null  float64
 22  they          316131 non-null  float64
 23  ipron         316131 non-null  float64
 24  article       316131 non-null  float64
 25  prep          316131 non-null  float64
 26  auxverb       316131 non-null  float64
 27  adverb        316131 non-null  float64
 28  conj          316131 non-null  float64
 29  negate        316131 non-null  float64
 30  verb          316131 non-null  float64
 31  adj           316131 non-null  float64
 32  compare       316131 non-null  float64
 33  interrog      316131 non-null  float64
 34  number        316131 non-null  float64
 35  quant         316131 non-null  float64
 36  affect        316131 non-null  float64
 37  posemo        316131 non-null  float64
 38  negemo        316131 non-null  float64
 39  anx           316131 non-null  float64
 40  anger         316131 non-null  float64
 41  sad           316131 non-null  float64
 42  social        316131 non-null  float64
 43  family        316131 non-null  float64
 44  friend        316131 non-null  float64
 45  female        316131 non-null  float64
 46  male          316131 non-null  float64
 47  cogproc       316131 non-null  float64
 48  insight       316131 non-null  float64
 49  cause         316131 non-null  float64
 50  discrep       316131 non-null  float64
 51  tentat        316131 non-null  float64
 52  certain       316131 non-null  float64
 53  differ        316131 non-null  float64
 54  percept       316131 non-null  float64
 55  see           316131 non-null  float64
 56  hear          316131 non-null  float64
 57  feel          316131 non-null  float64
 58  bio           316131 non-null  float64
 59  body          316131 non-null  float64
 60  health        316131 non-null  float64
 61  sexual        316131 non-null  float64
 62  ingest        316131 non-null  float64
 63  drives        316131 non-null  float64
 64  affiliation   316131 non-null  float64
 65  achieve       316131 non-null  float64
 66  power         316131 non-null  float64
 67  reward        316131 non-null  float64
 68  risk          316131 non-null  float64
 69  focuspast     316131 non-null  float64
 70  focuspresent  316131 non-null  float64
 71  focusfuture   316131 non-null  float64
 72  relativ       316131 non-null  float64
 73  motion        316131 non-null  float64
 74  space         316131 non-null  float64
 75  time          316131 non-null  float64
 76  work          316131 non-null  float64
 77  leisure       316131 non-null  float64
 78  home          316131 non-null  float64
 79  money         316131 non-null  float64
 80  relig         316131 non-null  float64
 81  death         316131 non-null  float64
 82  informal      316131 non-null  float64
 83  swear         316131 non-null  float64
 84  netspeak      316131 non-null  float64
 85  assent        316131 non-null  float64
 86  nonflu        316131 non-null  float64
 87  filler        316131 non-null  float64
 88  AllPunc       316131 non-null  float64
 89  Period        316131 non-null  float64
 90  Comma         316131 non-null  float64
 91  Colon         316131 non-null  float64
 92  SemiC         316131 non-null  float64
 93  QMark         316131 non-null  float64
 94  Exclam        316131 non-null  float64
 95  Dash          316131 non-null  float64
 96  Quote         316131 non-null  int64
 97  Apostro       316131 non-null  float64
 98  Parenth       316131 non-null  float64
 99  OtherP        316131 non-null  float64
dtypes: float64(91), int64(2), object(3), str(4)
memory usage: 476.4+ MB
None
\---Remaining Missing Values---
url         0
idvscore    1
reviewer    0
dateP       6
Rev         6
           ..
Dash        0
Quote       0
Apostro     0
Parenth     0
OtherP      0
Length: 100, dtype: int64