In [2]:
import pandas as pd

In [3]:
import openpyxl

In [4]:
Ex = pd.read_excel('ExpertReviewsClean43LIWC.xlsx')

In [5]:
Ex.shape

(238973, 98)

In [6]:
Ex.columns

Index(['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'WC', 'Analytic',
       'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function',
       'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron',
       'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj',
       'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo',
       'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male',
       'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ',
       'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual',
       'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk',
       'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion',
       'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death',
       'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler',
       'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam',
       'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP'],
      dtype='str')

In [7]:
Ex.head()

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,11.52,6.70,25.77,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,97.69,1.00,99.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,77.33,7.84,2.89,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,99.00,1.00,25.77,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,89.42,1.79,25.77,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

In [8]:
Ex['url'].nunique()
Ex['url'].value_counts()

url
https://www.metacritic.com/movie/dune-part-one                    67
https://www.metacritic.com/movie/no-time-to-die                   66
https://www.metacritic.com/movie/eternals                         62
https://www.metacritic.com/movie/west-side-story-2020             62
https://www.metacritic.com/movie/once-upon-a-time-in-hollywood    62
                                                                  ..
https://www.metacritic.com/movie/shot-in-the-heart                 7
https://www.metacritic.com/movie/siddhartha                        7
https://www.metacritic.com/movie/rocco-and-his-brothers            7
https://www.metacritic.com/movie/whiteout                          1
https://www.metacritic.com/movie/micmac---au-four-et-au-moulin     1
Name: count, Length: 11364, dtype: int64

In [9]:
vc = Ex['url'].value_counts()
vc.describe()

count    11364.000000
mean        21.028951
std         11.590415
min          1.000000
25%         11.000000
50%         18.000000
75%         30.000000
max         67.000000
Name: count, dtype: float64

In [10]:
(vc<5).sum()

np.int64(2)

In [11]:
(vc<7).sum()

np.int64(2)

In [12]:
(vc<8).sum()

np.int64(779)

In [13]:
(vc<10).sum()

np.int64(2122)

In [14]:
print(Ex['dateP'].isna().sum())
print(Ex['idvscore'].describe())
print(Ex['Rev'].isna().sum())

2
count    238971.000000
mean         62.718359
std          20.752696
min           0.000000
25%          50.000000
50%          63.000000
75%          78.000000
max         100.000000
Name: idvscore, dtype: float64
2

In [15]:
Ex.dtypes.value_counts()

float64    92
str         4
int64       2
Name: count, dtype: int64

In [16]:
Ex['dateP'].value_counts()

dateP
None              104482
'Feb 1, 2019'        180
'Jun 23, 2016'       160
'Sep 13, 2018'       152
'Dec 9, 2010'        152
                   ...
'Dec 13, 2014'         1
'Apr 19, 2014'         1
'Apr 20, 2014'         1
'Jun 28, 2014'         1
'Nov 2, 2014'          1
Name: count, Length: 3906, dtype: int64

In [17]:
Ex['Rev'].value_counts()

Rev
'None'                                                                                                                                                                                                                                                                    4565
'One of the best films of the year.'                                                                                                                                                                                                                                         8
'Fascinating.'                                                                                                                                                                                                                                                               7
'Riveting.'                                                                                                                                                                                                                                                                  7
'Spellbinding.'                                                                                                                                                                                                                                                              6
                                                                                                                                                                                                                                                                          ...
'This movie -- which is equally appealing to children (those of adventurous, non-freak-outable spirit), Japanese animation (anime) fans, and any surviving acquaintances of Timothy Leary -- is so full of invention, you might want to take a breather now and then.'       1
'Too intense for the youngest viewers, but teenagers will enjoy it -- an ill-smelling stink-god character is almost worthy of a Kevin Smith gross-out movie -- and grown-ups should find it diverting, if not exactly deep.'                                                 1
'Delivers chunks of Yellow Submarine and The Phantom Tollbooth -- a vividly timeless oddity suitable for many children and most stoners.'                                                                                                                                    1
'Has the power to transport us to a different place. The spark of special anime magic here is unmistakable and hard to resist.'                                                                                                                                              1
'A lovely, evocative tour de force. So why does it seem we should be enjoying it more?'                                                                                                                                                                                      1
Name: count, Length: 234186, dtype: int64

In [18]:
expert_clean = Ex.rename(columns={'idvscore':'review_score','dateP':'review_date','Rev':'review_text'})
expert_clean.columns

Index(['url', 'review_score', 'reviewer', 'review_date', 'review_text', 'WC',
       'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic',
       'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they',
       'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate',
       'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect',
       'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend',
       'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat',
       'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body',
       'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve',
       'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture',
       'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home',
       'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent',
       'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC',
       'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP'],
      dtype='str')

In [19]:
expert_clean['review_text'] = expert_clean['review_text'].str.strip(" '")

In [20]:
expert_clean['reviewer'] = expert_clean['reviewer'].str.strip(""" '" """)

In [21]:
expert_clean['review_date'] = expert_clean['review_date'].str.strip(" '")

In [22]:
expert_clean['reviewer'].value_counts()

reviewer
None                  25220
Roger Moore            3389
Peter Travers          3074
Roger Ebert            3051
James Berardinelli     3047
                      ...
Bill Muller               1
Hal Hinson                1
Troy Patterson            1
Joanna Weiss              1
Joe Mader                 1
Name: count, Length: 1185, dtype: int64

In [23]:
expert_clean['review_text'] = expert_clean['review_text'].replace("None",None)

In [24]:
expert_clean['review_text'].isna().sum()

np.int64(4567)

In [25]:
expert_clean.to_pickle('expert_clean.pkl')

In [26]:
expert_clean['reviewer'] = expert_clean['reviewer'].replace("None",None)

In [27]:
expert_clean['reviewer'].isna().sum()

np.int64(25222)

In [28]:
expert_clean['review_date'] = expert_clean['review_date'].replace("None", None)

In [29]:
expert_clean['review_date'].isna().sum()

np.int64(104484)

In [30]:
expert_clean['review_date'] = pd.to_datetime(expert_clean['review_date'])

In [33]:
expert_clean['review_date'].isna().sum()

np.int64(104484)

In [34]:
expert_clean['review_date'].dtype

dtype('<M8[us]')

In [35]:
expert_clean.duplicated().sum()

np.int64(27)

In [36]:
expert_clean[expert_clean.duplicated()]

,url,review_score,reviewer,review_date,review_text,WC,Analytic,Clout,Authentic,Tone,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
9417,https://www.metacritic.com/movie/bad-samaritan,20.0,Peter Bradshaw,2018-08-24,Given the nasty taste in the mouth that the fi...,22,99.00,50.00,31.94,1.00,...,4.55,0.0,0.0,0.0,0.0,0.00,0,9.09,0.00,0.0
26213,https://www.metacritic.com/movie/kusama---infi...,85.0,Lisa Jo Sagolla,2018-09-06,"Briskly paced, the film makes for a visually e...",52,98.48,77.92,2.90,25.77,...,5.77,0.0,0.0,0.0,0.0,1.92,0,3.85,3.85,0.0
48959,https://www.metacritic.com/movie/spiral-from-t...,46.0,Jacob Oller,2021-05-12,Spiral might have rhetorical wrinkles that set...,21,18.82,17.04,99.00,25.77,...,4.76,0.0,0.0,0.0,0.0,0.00,0,9.52,0.00,0.0
49980,https://www.metacritic.com/movie/voyagers,50.0,David Fear,2021-04-08,This is a pulpy B movie that is dying to be a ...,33,66.08,81.84,1.00,25.77,...,3.03,0.0,0.0,0.0,0.0,0.00,0,6.06,0.00,0.0
52471,https://www.metacritic.com/movie/last-letter-f...,50.0,Roger Moore,2021-07-26,The leads make this tolerable.,5,93.26,50.00,43.37,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,40.00,0.00,0.0
54300,https://www.metacritic.com/movie/worth,80.0,Robert Abele,2021-09-02,"What we re left with is, thankfully, sharp exc...",45,98.87,74.76,18.21,67.75,...,11.11,0.0,0.0,0.0,0.0,4.44,0,4.44,0.00,0.0
55857,https://www.metacritic.com/movie/sophie-jones,67.0,Michael Frank,2021-03-02,"Because of the personal subject matter, Jessie...",38,96.93,85.38,1.00,97.58,...,7.89,0.0,0.0,0.0,0.0,0.00,0,5.26,0.00,0.0
62481,https://www.metacritic.com/movie/mine-9,63.0,Roger Moore,2020-04-10,"Surprises may be few and far between, with eve...",49,81.96,41.92,21.80,4.76,...,8.16,0.0,0.0,0.0,0.0,2.04,0,4.08,0.00,0.0
73883,https://www.metacritic.com/movie/the-price-of-...,100.0,Maximilian Von Thun,2018-11-28,Nathaniel Kahn s The Price of Everything certa...,35,99.00,61.26,26.00,99.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0,5.71,0.00,0.0
82588,https://www.metacritic.com/movie/me-before-you,75.0,NaN,2016-06-02,Clarke and Claflin both turn in acutely human ...,28,93.26,85.81,30.01,87.20,...,7.14,0.0,0.0,0.0,0.0,0.00,0,7.14,0.00,0.0
82906,https://www.metacritic.com/movie/remember,80.0,Stephen Whitty,2016-03-09,See Remember. You won t regret it or forget it.,10,8.69,84.14,3.37,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,20.00,0.00,0.0
84571,https://www.metacritic.com/movie/neighbors-2-s...,60.0,NaN,2016-05-20,Just funny enough to not feel like a retread.,9,98.87,1.38,58.07,99.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0,22.22,0.00,0.0
94619,https://www.metacritic.com/movie/tesnota-close...,70.0,Allan Hunter,2020-04-30,"It is a grim, gruelling two hours that might b...",31,71.73,37.35,2.96,99.00,...,3.23,0.0,0.0,0.0,0.0,0.00,0,6.45,0.00,0.0
100569,https://www.metacritic.com/movie/the-climb,91.0,A.A. Dowd,2020-11-11,There are no sentimental easy answers or short...,40,90.61,30.86,15.86,99.00,...,5.00,0.0,0.0,0.0,0.0,0.00,0,5.00,0.00,0.0
122072,https://www.metacritic.com/movie/sorry-to-both...,80.0,Neil Smith,2018-12-03,"Wildly inventive, unpredictable, and unhinged,...",15,99.00,50.00,1.00,99.00,...,20.00,0.0,0.0,0.0,0.0,6.67,0,13.33,0.00,0.0
183062,https://www.metacritic.com/movie/down-to-you,25.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
183319,https://www.metacritic.com/movie/digimon-digit...,25.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
183352,https://www.metacritic.com/movie/highlander-en...,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
184074,https://www.metacritic.com/movie/gossip,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
184170,https://www.metacritic.com/movie/i-dreamed-of-...,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
184231,https://www.metacritic.com/movie/hanging-up,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
185744,https://www.metacritic.com/movie/bittersweet-m...,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
186119,https://www.metacritic.com/movie/the-6th-day,63.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
189524,https://www.metacritic.com/movie/mission-impos...,50.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0
196822,https://www.metacritic.com/movie/ice-age-the-m...,80.0,NaN,NaT,Reuniting the mismatched heroes from its hit p...,44,97.59,32.48,11.00,99.00,...,4.55,0.0,0.0,0.0,0.0,13.64,0,4.55,0.00,0.0
196831,https://www.metacritic.com/movie/ice-age-the-m...,75.0,Moira Macdonald,NaT,"Directed by Carlos Saldanha, who co-directed I...",35,95.52,38.74,13.15,99.00,...,5.71,0.0,0.0,0.0,0.0,5.71,0,5.71,5.71,0.0
208871,https://www.metacritic.com/movie/the-emperors-...,88.0,NaN,NaT,NaN,1,1.00,1.00,1.00,25.77,...,0.00,0.0,0.0,0.0,0.0,0.00,0,200.00,0.00,0.0

In [37]:
expert_clean = expert_clean.drop_duplicates()

In [40]:
expert_clean.shape

(238946, 98)

In [41]:
expert_clean.duplicated(subset=['url', 'reviewer', 'review_date', 'review_text']).sum()

np.int64(38)

In [43]:
expert_clean[expert_clean.duplicated(subset=['url', 'reviewer', 'review_date', 'review_text', 'review_score'], keep=False)]

Empty DataFrame
Columns: [url, review_score, reviewer, review_date, review_text, WC, Analytic, Clout, Authentic, Tone, WPS, Sixltr, Dic, function, pronoun, ppron, i, we, you, shehe, they, ipron, article, prep, auxverb, adverb, conj, negate, verb, adj, compare, interrog, number, quant, affect, posemo, negemo, anx, anger, sad, social, family, friend, female, male, cogproc, insight, cause, discrep, tentat, certain, differ, percept, see, hear, feel, bio, body, health, sexual, ingest, drives, affiliation, achieve, power, reward, risk, focuspast, focuspresent, focusfuture, relativ, motion, space, time, work, leisure, home, money, relig, death, informal, swear, netspeak, assent, nonflu, filler, AllPunc, Period, Comma, Colon, SemiC, QMark, Exclam, Dash, Quote, Apostro, Parenth, OtherP]
Index: []

[0 rows x 98 columns]

In [ ]:
expert_clean.insert(loc=0, column='expert_review_id', value=range(1, len(expert_clean) + 1))

ValueError: cannot insert expert_review_id, already exists

In [46]:
expert_clean.shape

(238946, 99)

In [47]:
expert_clean.head()

,expert_review_id,url,review_score,reviewer,review_date,review_text,WC,Analytic,Clout,Authentic,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,1,https://www.metacritic.com/movie/bronson,100.0,Andrew O'Hehir,NaT,Bronson owes a little or a lot to Kubrick s Cl...,25,73.88,11.52,6.70,...,4.00,0.00,0.0,0.0,0.0,0.00,0,8.00,0.0,0.0
1,2,https://www.metacritic.com/movie/bronson,90.0,A.O. Scott,NaT,Bronson invites you to admire its protagonist ...,30,13.07,97.69,1.00,...,6.67,0.00,0.0,0.0,0.0,0.00,0,6.67,0.0,0.0
2,3,https://www.metacritic.com/movie/bronson,90.0,NaN,NaT,Whether it s Peterson/Bronson s more theatrica...,40,72.69,77.33,7.84,...,7.50,0.00,0.0,0.0,0.0,12.50,0,5.00,0.0,2.5
3,4,https://www.metacritic.com/movie/bronson,83.0,Noel Murray,NaT,There are two Bronsons on display here: the im...,39,65.46,99.00,1.00,...,5.13,2.56,0.0,0.0,0.0,0.00,0,5.13,0.0,0.0
4,5,https://www.metacritic.com/movie/bronson,80.0,Joshua Rothkopf,NaT,Refn has somehow found his way to an authentic...,24,88.46,89.42,1.79,...,8.33,0.00,0.0,0.0,0.0,4.17,0,8.33,0.0,0.0

In [48]:
expert_clean.to_pickle('expert_clean.pkl')

In [3]:
expert_clean = pd.read_pickle('expert_clean.pkl')

In [4]:
expert_clean.to_csv('expert_clean.csv', index=False)

In [6]:
movie_tb = pd.read_csv('Movie.csv')

In [ ]:
movie_tb.columns

Index(['movie_id', 'url', 'title', 'year'], dtype='str')

In [12]:
expert_clean['url'].isin(movie_tb['url']).sum()

np.int64(238946)

In [13]:
movie_tb['url'].duplicated().sum()

np.int64(0)

In [17]:
movie_lookup = movie_tb[['movie_id','url']]

In [18]:
expert_clean = expert_clean.merge(movie_lookup, on='url', how='left')

In [19]:
expert_clean.shape

(238946, 100)

In [20]:
expert_clean['movie_id'].isna().sum()

np.int64(0)

In [21]:
expert_clean.to_csv('expert_clean.csv', index=False)

In [22]:
expert_clean.to_pickle('expert_clean.pkl')